version: "3.1"
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      FLASK_ENV: development
      REDIS_CACHE_HOSTNAME: redis
      REDIS_CACHE_PORT: 6379
      REDIS_CACHE_DATABASE: 0
      REQUEST_PASSWORD: qwerty
      PROVIDER_API_KEY: apikey
      CORNERSHOP_WEBHOOK_URL: /webhook
      CORNERSHOP_WEBHOOK_PASSWORD: password
      PROVIDER_HOST: api:8000
    volumes:
      - ./src:/opt/cornershop/api